package br.com.shubudo.utils

fun Int.toOrdinario(): String {
    return when (this) {
        1 -> "Primeiro"
        2 -> "Segundo"
        3 -> "Terceiro"
        4 -> "Quarto"
        5 -> "Quinto"
        6 -> "Sexto"
        7 -> "Sétimo"
        8 -> "Oitavo"
        9 -> "Nono"
        10 -> "Décimo"
        11 -> "Décimo Primeiro"
        12 -> "Décimo Segundo"
        13 -> "Décimo Terceiro"
        14 -> "Décimo Quarto"
        15 -> "Décimo Quinto"
        16 -> "Décimo Sexto"
        17 -> "Décimo Sétimo"
        18 -> "Décimo Oitavo"
        19 -> "Décimo Nono"
        20 -> "Vigésimo"
        21 -> "Vigésimo Primeiro"
        22 -> "Vigésimo Segundo"
        23 -> "Vigésimo Terceiro"
        24 -> "Vigésimo Quarto"
        25 -> "Vigésimo Quinto"
        26 -> "Vigésimo Sexto"
        27 -> "Vigésimo Sétimo"
        28 -> "Vigésimo Oitavo"
        29 -> "Vigésimo Nono"
        30 -> "Trigésimo"
        31 -> "Trigésimo Primeiro"
        32 -> "Trigésimo Segundo"
        33 -> "Trigésimo Terceiro"
        34 -> "Trigésimo Quarto"
        35 -> "Trigésimo Quinto"
        36 -> "Trigésimo Sexto"
        37 -> "Trigésimo Sétimo"
        38 -> "Trigésimo Oitavo"
        39 -> "Trigésimo Nono"
        40 -> "Quadragésimo"
        41 -> "Quadragésimo Primeiro"
        42 -> "Quadragésimo Segundo"
        43 -> "Quadragésimo Terceiro"
        44 -> "Quadragésimo Quarto"
        45 -> "Quadragésimo Quinto"
        46 -> "Quadragésimo Sexto"
        47 -> "Quadragésimo Sétimo"
        48 -> "Quadragésimo Oitavo"
        49 -> "Quadragésimo Nono"
        50 -> "Quinquagésimo"
        51 -> "Quinquagésimo Primeiro"
        52 -> "Quinquagésimo Segundo"
        53 -> "Quinquagésimo Terceiro"
        54 -> "Quinquagésimo Quarto"
        55 -> "Quinquagésimo Quinto"
        56 -> "Quinquagésimo Sexto"
        57 -> "Quinquagésimo Sétimo"
        58 -> "Quinquagésimo Oitavo"
        59 -> "Quinquagésimo Nono"
        60 -> "Sexagésimo"
        else -> "Número não suportado"
    }
}

fun Int.toOrdinarioFeminino(): String {
    return when (this) {
        1 -> "Primeira"
        2 -> "Segunda"
        3 -> "Terceira"
        4 -> "Quarta"
        5 -> "Quinta"
        6 -> "Sexta"
        7 -> "Sétima"
        8 -> "Oitava"
        9 -> "Nona"
        10 -> "Décima"
        11 -> "Décima Primeira"
        12 -> "Décima Segunda"
        13 -> "Décima Terceira"
        14 -> "Décima Quarta"
        15 -> "Décima Quinta"
        16 -> "Décima Sexta"
        17 -> "Décima Sétima"
        18 -> "Décima Oitava"
        19 -> "Décima Nona"
        20 -> "Vigésima"
        21 -> "Vigésima Primeira"
        22 -> "Vigésima Segunda"
        23 -> "Vigésima Terceira"
        24 -> "Vigésima Quarta"
        25 -> "Vigésima Quinta"
        26 -> "Vigésima Sexta"
        27 -> "Vigésima Sétima"
        28 -> "Vigésima Oitava"
        29 -> "Vigésima Nona"
        30 -> "Trigésima"
        31 -> "Trigésima Primeira"
        32 -> "Trigésima Segunda"
        33 -> "Trigésima Terceira"
        34 -> "Trigésima Quarta"
        35 -> "Trigésima Quinta"
        36 -> "Trigésima Sexta"
        37 -> "Trigésima Sétima"
        38 -> "Trigésima Oitava"
        39 -> "Trigésima Nona"
        40 -> "Quadragésima"
        41 -> "Quadragésima Primeira"
        42 -> "Quadragésima Segunda"
        43 -> "Quadragésima Terceira"
        44 -> "Quadragésima Quarta"
        45 -> "Quadragésima Quinta"
        46 -> "Quadragésima Sexta"
        47 -> "Quadragésima Sétima"
        48 -> "Quadragésima Oitava"
        49 -> "Quadragésima Nona"
        50 -> "Quinquagésima"
        51 -> "Quinquagésima Primeira"
        52 -> "Quinquagésima Segunda"
        53 -> "Quinquagésima Terceira"
        54 -> "Quinquagésima Quarta"
        55 -> "Quinquagésima Quinta"
        56 -> "Quinquagésima Sexta"
        57 -> "Quinquagésima Sétima"
        58 -> "Quinquagésima Oitava"
        59 -> "Quinquagésima Nona"
        60 -> "Sexagésima"
        else -> "Número não suportado"
    }
}
